config/routes.rb
VehicleComplaints::Application.routes.draw do
  resources :complaints

  resources :users 

  root to: "users#new"

end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  attr_accessible :bus_stop_name, :charged_and_allowed_other_complainant, :charged_for_luggage, :excess_charged, :fault_no_working_meter, :fly_destination, :from_to_fly, :from_to_luggage, :indecent_behaviour, :occurence_date_time, :other_complaints, :place_occurence, :user_id, :vehicle_attributes

  belongs_to :user
  has_one :vehicle
  accepts_nested_attributes_for :vehicle
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :address, :email, :mobile, :name , :complaints_attributes

  has_many :complaints
  accepts_nested_attributes_for :complaints 

  validates_presence_of :email ,  :name , :mobile


  
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  attr_accessible :vehicle_number, :vehicle_types

  belongs_to :complaint

  validates_presence_of :vehicle_types , :vehicle_number


  def self.vehicle_types
  	@types=  ["Auto","Taxi","Bus"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @complaints }
    end
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
    @complaint = Complaint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @complaint }
    end
  end

  # GET /complaints/new
  # GET /complaints/new.json
  def new
    @complaint = Complaint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @complaint }
    end
  end

  # GET /complaints/1/edit
  def edit
    @complaint = Complaint.find(params[:id])
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(params[:complaint])

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        format.json { render json: @complaint, status: :created, location: @complaint }
      else
        format.html { render action: "new" }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /complaints/1
  # PUT /complaints/1.json
  def update
    @complaint = Complaint.find(params[:id])

    respond_to do |format|
      if @complaint.update_attributes(params[:complaint])
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint = Complaint.find(params[:id])
    @complaint.destroy

    respond_to do |format|
      format.html { redirect_to complaints_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @user.complaints.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Complaint was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { redirect_to root_path }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/complaints/_form.html.erb
<%= form_for @complaint, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :fly_destination, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :fly_destination, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :from_to_fly, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :from_to_fly, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :excess_charged, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :excess_charged, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :indecent_behaviour, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :indecent_behaviour, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :charged_and_allowed_other_complainant, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :charged_and_allowed_other_complainant, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :charged_for_luggage, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :charged_for_luggage, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :from_to_luggage, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :from_to_luggage, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bus_stop_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :bus_stop_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :other_complaints, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :other_complaints, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :occurence_date_time, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :occurence_date_time, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :place_occurence, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :place_occurence, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :fault_no_working_meter, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :fault_no_working_meter, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                complaints_path, :class => 'btn' %>
  </div>
<% end %>

app/views/complaints/edit.html.erb
<%- model_class = Complaint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/complaints/index.html.erb
<%- model_class = Complaint -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:fly_destination) %></th>
      <th><%= model_class.human_attribute_name(:from_to_fly) %></th>
      <th><%= model_class.human_attribute_name(:excess_charged) %></th>
      <th><%= model_class.human_attribute_name(:indecent_behaviour) %></th>
      <th><%= model_class.human_attribute_name(:charged_and_allowed_other_complainant) %></th>
      <th><%= model_class.human_attribute_name(:charged_for_luggage) %></th>
      <th><%= model_class.human_attribute_name(:from_to_luggage) %></th>
      <th><%= model_class.human_attribute_name(:bus_stop_name) %></th>
      <th><%= model_class.human_attribute_name(:other_complaints) %></th>
      <th><%= model_class.human_attribute_name(:occurence_date_time) %></th>
      <th><%= model_class.human_attribute_name(:place_occurence) %></th>
      <th><%= model_class.human_attribute_name(:fault_no_working_meter) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= link_to complaint.id, complaint_path(complaint) %></td>
        <td><%= complaint.fly_destination %></td>
        <td><%= complaint.from_to_fly %></td>
        <td><%= complaint.excess_charged %></td>
        <td><%= complaint.indecent_behaviour %></td>
        <td><%= complaint.charged_and_allowed_other_complainant %></td>
        <td><%= complaint.charged_for_luggage %></td>
        <td><%= complaint.from_to_luggage %></td>
        <td><%= complaint.bus_stop_name %></td>
        <td><%= complaint.other_complaints %></td>
        <td><%= complaint.occurence_date_time %></td>
        <td><%= complaint.place_occurence %></td>
        <td><%= complaint.fault_no_working_meter %></td>
        <td><%=l complaint.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_complaint_path(complaint), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      complaint_path(complaint),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_complaint_path,
            :class => 'btn btn-primary' %>

app/views/complaints/new.html.erb
<%- model_class = Complaint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/complaints/show.html.erb
<%- model_class = Complaint -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:fly_destination) %>:</strong></dt>
  <dd><%= @complaint.fly_destination %></dd>
  <dt><strong><%= model_class.human_attribute_name(:from_to_fly) %>:</strong></dt>
  <dd><%= @complaint.from_to_fly %></dd>
  <dt><strong><%= model_class.human_attribute_name(:excess_charged) %>:</strong></dt>
  <dd><%= @complaint.excess_charged %></dd>
  <dt><strong><%= model_class.human_attribute_name(:indecent_behaviour) %>:</strong></dt>
  <dd><%= @complaint.indecent_behaviour %></dd>
  <dt><strong><%= model_class.human_attribute_name(:charged_and_allowed_other_complainant) %>:</strong></dt>
  <dd><%= @complaint.charged_and_allowed_other_complainant %></dd>
  <dt><strong><%= model_class.human_attribute_name(:charged_for_luggage) %>:</strong></dt>
  <dd><%= @complaint.charged_for_luggage %></dd>
  <dt><strong><%= model_class.human_attribute_name(:from_to_luggage) %>:</strong></dt>
  <dd><%= @complaint.from_to_luggage %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bus_stop_name) %>:</strong></dt>
  <dd><%= @complaint.bus_stop_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:other_complaints) %>:</strong></dt>
  <dd><%= @complaint.other_complaints %></dd>
  <dt><strong><%= model_class.human_attribute_name(:occurence_date_time) %>:</strong></dt>
  <dd><%= @complaint.occurence_date_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:place_occurence) %>:</strong></dt>
  <dd><%= @complaint.place_occurence %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fault_no_working_meter) %>:</strong></dt>
  <dd><%= @complaint.fault_no_working_meter %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              complaints_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_complaint_path(@complaint), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              complaint_path(@complaint),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/_contact_details.html.erb
<p>
Note :-

1. You can also complaint by other sources.

2. Complainants name will not be disclosed.

3. You can also send complaint on 
transportcommissioner@trafficpolicemumbai.org, 
rto.tardeo@trafficpolicemumbai.org, 
rto.andheri@trafficpolicemumbai.org 
rto.wadala@trafficpolicemumbai.org
</p>

 
</p>
<strong>Regional Transport Office – RTO in Andheri</strong>

Address: Regional Transport Office, D/111, Ambivali Village, Versova Road, Near Manish Nagar, Andheri (West), Mumbai, Pincode – 400053.
Telephone Number: 6362252, 26366957, 26319821
</p>

</p>
<strong>Regional Transport Office – RTO in Ghatkopar</strong>
Telephone Number: 25115202
</p>

</p>
<strong>Regional Transport Office – RTO in Thane</strong>
Telephone Number: 25340474
</p>

</p>
<strong>Regional Transport Office – RTO in Worli</strong>
Address: 25/Sir Pochkhanwala Road, Worli, Pincode : 400025, Mumbai

Telephone Number: 25340474
</p>

<p>
<strong>Regional Transport Office – RTO in Wadala</strong>
Address: B/2, 3rd Flr, Wadala Truck Terminal, Wadala Road, Pincode : 400037
</p>

<p> 
<strong>Regional Transport Office – RTO In Tardeo</strong>
Address: Old Bodyguard Lane, Tulsiwadi Tardeo, Mumbai, Pincode – 400034.
Telephone Number: 24944600, 24932337, 24944601, 24944602
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VehicleComplaints</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>

	<header id="overview" class="jumbotron subhead">
		<div class="container">
			<h1>Public Transportation Complaint</h1>
			<p class="lead">Make public transportation better</p>
		</div>
	</header>

<div class = "container">
  <div class="row">
	  <div class="span9"><%= yield %></div>
    <div class="span3">
    	<h3>Other Contact Details</h3>
      <%= render :partial => "layouts/contact_details" %>
    </div>
  </div>

</div>

</body>
</html>

app/views/users/_complaint_form.html.erb
<%= f.fields_for :complaints, :html => { :class => 'form-horizontal' } do |builder| %>

  <%= f.fields_for :vehicle do |vehicle_builder| %>
    
  <div class="control-group">
    <%= vehicle_builder.label :vehicle_types , "Mode of Transportation" %>
    <div class="controls">
      <%= vehicle_builder.select :vehicle_types , [["- Select a Mode-", nil]] + Vehicle.vehicle_types.collect {|p| p}, :id => "vehicle_types" %>
    </div>
  </div>
  <div class="control-group">
     <%= vehicle_builder.label :number , "Vehicle Number"  %>
    <div class="controls">
      <%= vehicle_builder.text_field :number  %>
    </div>
 </div>
      <% end %>
  <div class="control-group">
    <%= builder.label :place_occurence, "Place Where The Incident Happened",:class => 'control-label' %>
    <div class="controls">
      <%= builder.text_field :place_occurence, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= builder.label :fault_no_working_meter, :class => 'control-label' %>
    <div class="controls">
      <%= builder.check_box :fault_no_working_meter, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group" id = "required_destination">
    <%= builder.label :fly_destination, "Refused to go the required destination" , :class => 'control-label' %>
    <div class="controls">
      <%= builder.check_box :fly_destination, :class => 'check_box' ,  :id => "refused_checkbox" %>
    </div>
  </div>
  <div class="control-group" id = "refused_from_to" style = "display:none" >
    <%= builder.label :from_to_fly, "From-To",:class => 'control-label' %>
    <div class="controls">
      <%= builder.text_field :from_to_fly,:placeholder => "Ex :Raghuleela Mall - Kandivili station" ,:class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= builder.label :excess_charged, :class => 'control-label' %>
    <div class="controls">
      <%= builder.check_box :excess_charged, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= builder.label :indecent_behaviour, "Inappropriate Behaviour" , :class => 'control-label' %>
    <div class="controls">
      <%= builder.check_box :indecent_behaviour, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= builder.label :charged_and_allowed_other_complainant, "Charged fare from other passenger and allowed to travel",  :class => 'control-label' %>
    <div class="controls">
      <%= builder.check_box :charged_and_allowed_other_complainant, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= builder.label :charged_for_luggage, "Enter the Amount Excessively Charged for Luggage " , :class => 'control-label' %>
    <div class="controls">
      <%= builder.number_field :charged_for_luggage, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= builder.label :from_to_luggage,"From-To", :class => 'control-label' %>
    <div class="controls">
      <%= builder.text_field :from_to_luggage, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group"  id = "bus_stop" style = "display:none" >
    <%= builder.label :bus_stop_name,:class => 'control-label' %>
    <div class="controls">
      <%= builder.text_field :bus_stop_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= builder.label :other_complaints, :class => 'control-label' %>
    <div class="controls">
      <%= builder.text_area :other_complaints, size: "30x10" ,:style => "width: 369px; height: 119px;" ,:class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= builder.label :occurence_date_time, :class => 'control-label' %>
    <div class="controls">
      <%= builder.datetime_select :occurence_date_time, :class => 'datetime_select' %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mobile, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mobile, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  
  <%=render "complaint_form", f: f %>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:mobile) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.mobile %></td>
        <td><%= user.address %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile) %>:</strong></dt>
  <dd><%= @user.mobile %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @user.address %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>